version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai-trading-bot-postgres
    environment:
      POSTGRES_DB: trading_bot
      POSTGRES_USER: trading_bot
      POSTGRES_PASSWORD: ${DB_PASSWORD:-trading_bot_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_bot -d trading_bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trading-bot-network

  redis:
    image: redis:7-alpine
    container_name: ai-trading-bot-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-redis_password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trading-bot-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  trading-bot-network:
    driver: bridge